package com.compliance.db.compliance_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE ComplianceBase PLEASE EDIT ../Compliance.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Compliance object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;

import org.springframework.jdbc.core.RowMapper;
import com.compliance.db.compliance_db.entity.Compliance;

public class ComplianceBase implements RowMapper<Compliance>{
	
	private Long _id;
	
	// Attributes
    private Date ApprovedDate;
    private String AprroverName;
    private String Compliance_id;
    private String CreatedBy;
    private Boolean IsActive;
    private String LawType;
    private String Penalty;
    private String PublishedBy;
    private Date PublishedOn;
    private String Regulator;
    private String Section;
    private String Version;
    private Date createdDate;
	
	
	
	@Override
	public Compliance mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Compliance obj = new Compliance();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setApprovedDate(rs.getDate("ApprovedDate"));
			obj.setAprroverName(rs.getString("AprroverName"));
			obj.setCompliance_id(rs.getString("Compliance_id"));
			obj.setCreatedBy(rs.getString("CreatedBy"));
			obj.setIsActive(rs.getBoolean("IsActive"));
			obj.setLawType(rs.getString("LawType"));
			obj.setPenalty(rs.getString("Penalty"));
			obj.setPublishedBy(rs.getString("PublishedBy"));
			obj.setPublishedOn(rs.getDate("PublishedOn"));
			obj.setRegulator(rs.getString("Regulator"));
			obj.setSection(rs.getString("Section"));
			obj.setVersion(rs.getString("Version"));
			obj.setCreatedDate(rs.getDate("createdDate"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public Date getApprovedDate() {
		return ApprovedDate;
	}


	public void setApprovedDate(Date ApprovedDate) {
		this.ApprovedDate = ApprovedDate;
	}
	public String getAprroverName() {
		return AprroverName;
	}


	public void setAprroverName(String AprroverName) {
		this.AprroverName = AprroverName;
	}
	public String getCompliance_id() {
		return Compliance_id;
	}


	public void setCompliance_id(String Compliance_id) {
		this.Compliance_id = Compliance_id;
	}
	public String getCreatedBy() {
		return CreatedBy;
	}


	public void setCreatedBy(String CreatedBy) {
		this.CreatedBy = CreatedBy;
	}
	public Boolean getIsActive() {
		return IsActive;
	}


	public void setIsActive(Boolean IsActive) {
		this.IsActive = IsActive;
	}
	public String getLawType() {
		return LawType;
	}


	public void setLawType(String LawType) {
		this.LawType = LawType;
	}
	public String getPenalty() {
		return Penalty;
	}


	public void setPenalty(String Penalty) {
		this.Penalty = Penalty;
	}
	public String getPublishedBy() {
		return PublishedBy;
	}


	public void setPublishedBy(String PublishedBy) {
		this.PublishedBy = PublishedBy;
	}
	public Date getPublishedOn() {
		return PublishedOn;
	}


	public void setPublishedOn(Date PublishedOn) {
		this.PublishedOn = PublishedOn;
	}
	public String getRegulator() {
		return Regulator;
	}


	public void setRegulator(String Regulator) {
		this.Regulator = Regulator;
	}
	public String getSection() {
		return Section;
	}


	public void setSection(String Section) {
		this.Section = Section;
	}
	public String getVersion() {
		return Version;
	}


	public void setVersion(String Version) {
		this.Version = Version;
	}
	public Date getCreatedDate() {
		return createdDate;
	}


	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
    
    
    
    
}